version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'babel-loader'
          - 'webpack'
          - 'webpack-*'
          - 'terser-webpack-plugin'

      lint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - 'neostandard'
          - 'stylelint'
          - 'stylelint-*'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'

      defra:
        patterns:
          - '@defra/*'

      hapi:
        patterns:
          - '@hapi/*'
          - 'blankie'
          - 'hapi-*'

      tools:
        patterns:
          - 'husky'
          - 'vitest'
          - 'vitest-*'
          - 'nodemon'
          - 'npm-run-all'
          - 'lodash'
          - 'source-map-loader'
          - 'sass-*'
          - 'postcss-*'
          - 'cheerio'
          - 'clean-webpack-plugin'
          - 'copy-webpack-plugin'

      types:
        patterns:
          - '@types/*'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
