version: '3.4'
services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  elasticsearch:
    image: elasticsearch:7.17.15
    ports:
      - '9200:9200'
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      cluster.routing.allocation.disk.threshold_enabled: 'false'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 10s
      start_period: 30s
      retries: 5
    networks:
      - cdp-tenant

  geonetwork:
    image: geonetwork:4.2
    ports:
      - '8080:8080'
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ES_HOST: elasticsearch
      ES_PORT: 9200
      ES_PROTOCOL: http
      GEONETWORK_ES_HOST: elasticsearch
      GEONETWORK_ES_PORT: 9200
      GEONETWORK_ES_PROTOCOL: http
      JAVA_OPTS: '-Xms512m -Xmx512m'
    networks:
      - cdp-tenant

networks:
  cdp-tenant:
    driver: bridge
